// Section 11
// Random Numbers
// Tip: I use cpp methods not c methods like the video in the course

#include <iostream>
#include <random>      // c++ library, also c library is available but not recommended

using namespace std;

int main() {

    // std::default_random_engine generates pseudo random numbers.
    // std::random_device generates true random numbers.

    random_device rd;  // Will be used to obtain a seed for the random number engine
    mt19937_64 gen(rd());  // Standard mersenne_twister_engine seeded with rd().
                               // To set SEED change rd() with, for example, 42
    uniform_int_distribution<int> distrib(1, 6);

    for (int n=0; n<10; ++n)
        // Use `distrib` to transform the random unsigned int generated by gen into an int in [1, 6]
        cout << distrib(gen) << ' ';

    cout  << endl;
    return 0;
}

